sudo: required

language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:1.6.2:war -Dmdep.stripVersion=true
  - java -jar ./target/dependency/cargo-daemon-webapp.war &

script:
  - ./mvnw -U package
