sudo: required

language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./mvnw -U package -Dwdm.gitHubTokenName=${WDM_GITHUB_USER} -Dwdm.gitHubTokenSecret=${WDM_GITHUB_TOKEN}
