sudo: required

language: java

jdk:
  - oraclejdk8

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

script:
  - |
    if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" == "true" ]; then
        ./mvnw -U install
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
        ./mvnw -U org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN}
    fi
