sudo: required

language: java


matrix:
  include:
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install: true

script:
  - |
    if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" == "true" ]; then
        ./mvnw -U verify jacoco:report coveralls:report
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
        ./mvnw -U verify jacoco:report coveralls:report sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN}
    fi
